print("hello"[2])
print(3 != 2)
print(str(110))
print(str("110"))
print(8 == 8)
print("hello"[2])
print(3 * "hello")
print(2.0**2)
print(2**2.0)
print(not not True)
print(not True)
print(not True and not True)
print(not True or not False)
print(not False or not False)
print(True and False or False and not False)
